version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "6379:6379"
    
